const { IoTClient, CreateThingCommand, CreateKeysAndCertificateCommand,
        AttachPolicyCommand, AttachThingPrincipalCommand,
        AddThingToThingGroupCommand, DescribeEndpointCommand } = require('@aws-sdk/client-iot');
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');

const iot = new IoTClient({});
const s3 = new S3Client({});

const POLICY_NAME = process.env.IOT_POLICY_NAME || 'ESP32-Patient-Monitor-Policy';
const BUNDLE_BUCKET = process.env.BUNDLE_BUCKET;

/**
 * Provisions one device and returns a short-lived link to its credentials.
 *
 * The private key is the reason this is shaped the way it is: AWS returns it
 * exactly once, at creation, and never again. It is written straight to S3 and
 * surfaced as a pre-signed URL that expires. It is never returned in this
 * response body and never stored in Salesforce - so it stays out of CRM
 * backups, exports and reports.
 */
exports.handler = async (event) => {
  const body = typeof event.body === 'string' ? JSON.parse(event.body) : event;
  const { thingName, thingGroup = 'patient-monitors', ssid, passphrase, ttlMinutes = 15 } = body;

  if (!thingName || !ssid) {
    return respond(400, { error: 'thingName and ssid are required' });
  }

  try {
    const { thingArn } = await iot.send(new CreateThingCommand({ thingName }));

    // Keys are generated by AWS and returned once. Nothing here logs them.
    const cert = await iot.send(new CreateKeysAndCertificateCommand({ setAsActive: true }));

    await iot.send(new AttachPolicyCommand({
      policyName: POLICY_NAME,
      target: cert.certificateArn,
    }));
    await iot.send(new AttachThingPrincipalCommand({
      thingName,
      principal: cert.certificateArn,
    }));
    // Group membership is what OTA Jobs target. Without this the device is
    // reachable but invisible to fleet rollouts.
    await iot.send(new AddThingToThingGroupCommand({ thingName, thingGroupName: thingGroup }));

    const { endpointAddress } = await iot.send(new DescribeEndpointCommand({
      endpointType: 'iot:Data-ATS',
    }));

    // Everything the device needs, in the shape its serial provisioning mode
    // expects. One file, one paste, no per-device firmware build.
    const bundle = {
      thingName,
      endpoint: endpointAddress,
      ssid,
      passphrase,
      certificatePem: cert.certificatePem,
      privateKey: cert.keyPair.PrivateKey,
    };

    const key = `provisioning/${thingName}-${Date.now()}.json`;
    await s3.send(new PutObjectCommand({
      Bucket: BUNDLE_BUCKET,
      Key: key,
      Body: JSON.stringify(bundle, null, 2),
      ContentType: 'application/json',
      ServerSideEncryption: 'AES256',
    }));

    const bundleUrl = await getSignedUrl(
      s3,
      new PutObjectCommand({ Bucket: BUNDLE_BUCKET, Key: key }),
      { expiresIn: ttlMinutes * 60 }
    );

    console.log('provisioned', { thingName, thingGroup, certificateId: cert.certificateId });

    return respond(200, {
      thingArn,
      certificateId: cert.certificateId,
      thingGroup,
      bundleUrl,
      expiresInMinutes: ttlMinutes,
    });
  } catch (err) {
    console.error('provisioning failed', { thingName, error: err.message });
    return respond(500, { error: err.message });
  }
};

function respond(statusCode, body) {
  return { statusCode, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) };
}
